"""
Canonical Catalogue of OHADA Legal Texts.
"""

from typing import Any

OHADA_CATALOGUE: dict[str, dict[str, Any]] = {
    "TRAITE": {
        "code": "TRAITE",
        "name": "Traité OHADA révisé",
        "full_name": "Traité relatif à l'harmonisation du droit des affaires en Afrique",
        "year": 2008,
        "adopted_at": "2008-10-17",
        "published_at": "2008-11-01",
        "effective_date": "2008-09-12",
        "file": "TRAITE-OHADA-2008_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA",
        "url": "https://www.ohada.org/traite-ohada/",
        "description": "Traité fondateur instituant l'Organisation pour l'Harmonisation en Afrique du Droit des Affaires (OHADA).",
    },
    "AUDCG": {
        "code": "AUDCG",
        "name": "Acte Uniforme — Droit Commercial Général",
        "full_name": "Acte Uniforme portant sur le Droit Commercial Général",
        "year": 2010,
        "adopted_at": "2010-12-15",
        "published_at": "2011-02-15",
        "effective_date": "2011-05-15",
        "file": "AUDCG-2010_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° 23",
        "url": "https://www.ohada.org/actes-uniformes/audcg-2010/",
        "description": "Statut du commerçant et de l'entreprenant, registre du commerce et du crédit mobilier (RCCM), bail à usage professionnel et fonds de commerce, vente commerciale et intermédiaires de commerce.",
    },
    "AUSCGIE": {
        "code": "AUSCGIE",
        "name": "Acte Uniforme — Sociétés Commerciales & GIE",
        "full_name": "Acte Uniforme relatif au Droit des Sociétés Commerciales et du Groupement d'Intérêt Économique",
        "year": 2014,
        "adopted_at": "2014-01-30",
        "published_at": "2014-02-04",
        "effective_date": "2014-05-05",
        "file": "AUSCGIE-2014_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° spécial du 04/02/2014",
        "url": "https://www.ohada.org/actes-uniformes/auscgie-2014/",
        "description": "Règles de constitution, fonctionnement, restructuration et dissolution des sociétés (SARL, SA, SAS, SNC, SCS) et GIE.",
    },
    "AUPCAP": {
        "code": "AUPCAP",
        "name": "Acte Uniforme — Procédures Collectives",
        "full_name": "Acte Uniforme portant Organisation des Procédures Collectives d'Apurement du Passif",
        "year": 2015,
        "adopted_at": "2015-09-10",
        "published_at": "2015-09-25",
        "effective_date": "2015-12-24",
        "file": "AUPCAP-2015_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° spécial du 25/09/2015",
        "url": "https://www.ohada.org/actes-uniformes/aupcap-2015/",
        "description": "Procédures de prévention et de traitement des difficultés des entreprises : conciliation, règlement préventif, redressement judiciaire et liquidation des biens.",
    },
    "AUS": {
        "code": "AUS",
        "name": "Acte Uniforme — Sûretés",
        "full_name": "Acte Uniforme portant Organisation des Sûretés",
        "year": 2010,
        "adopted_at": "2010-12-15",
        "published_at": "2011-02-15",
        "effective_date": "2011-05-15",
        "file": "AUS-2010_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° 22",
        "url": "https://www.ohada.org/actes-uniformes/aus-2010/",
        "description": "Règime des garanties personnelles (cautionnement, garantie autonome) et réelles (hypothèque, gage, nantissement, privilèges).",
    },
    "AUA": {
        "code": "AUA",
        "name": "Acte Uniforme — Arbitrage",
        "full_name": "Acte Uniforme relatif au Droit de l'Arbitrage",
        "year": 2017,
        "adopted_at": "2017-11-23",
        "published_at": "2017-12-15",
        "effective_date": "2018-03-15",
        "file": "AUA-2017_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° spécial du 15/12/2017",
        "url": "https://www.ohada.org/actes-uniformes/aua-2017/",
        "description": "Cadre général des instances arbitrales, de la convention d'arbitrage et de la reconnaissance/exécution des sentences.",
    },
    "AUM": {
        "code": "AUM",
        "name": "Acte Uniforme — Médiation",
        "full_name": "Acte Uniforme relatif à la Médiation",
        "year": 2017,
        "adopted_at": "2017-11-23",
        "published_at": "2017-12-15",
        "effective_date": "2018-03-15",
        "file": "AUM-2017_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° spécial du 15/12/2017",
        "url": "https://www.ohada.org/actes-uniformes/aum-2017/",
        "description": "Cadre juridique du processus de médiation conventionnelle et judiciaire dans l'espace OHADA.",
    },
    "AUDCIF": {
        "code": "AUDCIF",
        "name": "Acte Uniforme — Droit Comptable (SYSCOHADA)",
        "full_name": "Acte Uniforme relatif au Droit Comptable et à l'Information Financière",
        "year": 2017,
        "adopted_at": "2017-01-26",
        "published_at": "2017-02-15",
        "effective_date": "2018-01-01",
        "file": "AUDCIF-2017_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° spécial du 15/02/2017",
        "url": "https://www.ohada.org/actes-uniformes/audcif-2017/",
        "description": "Système comptable OHADA révisé (SYSCOHADA révisé) et règles de présentation des états financiers de synthèse.",
    },
    "AUSCOOP": {
        "code": "AUSCOOP",
        "name": "Acte Uniforme — Sociétés Coopératives",
        "full_name": "Acte Uniforme relatif au Droit des Sociétés Coopératives",
        "year": 2010,
        "adopted_at": "2010-12-15",
        "published_at": "2011-02-15",
        "effective_date": "2011-05-15",
        "file": "AUSCOOP-2010_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° 23",
        "url": "https://www.ohada.org/actes-uniformes/auscoop-2010/",
        "description": "Règles relatives aux sociétés coopératives simplifiées et avec conseil d'administration.",
    },
    "AUCTMR": {
        "code": "AUCTMR",
        "name": "Acte Uniforme — Transport de Marchandises",
        "full_name": "Acte Uniforme relatif aux Contrats de Transport de Marchandises par Route",
        "year": 2003,
        "adopted_at": "2003-03-22",
        "published_at": "2003-05-01",
        "effective_date": "2004-01-01",
        "file": "AUCTMR-2003_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° 13",
        "url": "https://www.ohada.org/actes-uniformes/auctmr-2003/",
        "description": "Prise en charge, exécution, responsabilité du transporteur et réclamations en matière de transport routier inter-États.",
    },
    "AUPSRVE": {
        "code": "AUPSRVE",
        "name": "Acte Uniforme — Recouvrement & Voies d'Exécution",
        "full_name": "Acte Uniforme portant Organisation des Procédures Simplifiées de Recouvrement et des Voies d'Exécution",
        "year": 2023,
        "adopted_at": "2023-10-17",
        "published_at": "2023-11-17",
        "effective_date": "2024-02-16",
        "file": "AUPSRVE-2023_fr.pdf",
        "publisher": "Secrétariat Permanent de l'OHADA",
        "publication": "Journal Officiel de l'OHADA n° spécial du 17/11/2023",
        "url": "https://www.ohada.org/actes-uniformes/aupsrve-2023/",
        "description": "Injonction de payer, injonction de délivrer ou de restituer, saisies conservatoires et saisies-exécutions révisées.",
    },
    "REGLEMENT-ARBITRAGE-CCJA": {
        "code": "REGLEMENT-ARBITRAGE-CCJA",
        "name": "Règlement d'Arbitrage CCJA",
        "full_name": "Règlement d'Arbitrage de la Cour Commune de Justice et d'Arbitrage de l'OHADA",
        "year": 2017,
        "adopted_at": "2017-11-23",
        "published_at": "2017-12-15",
        "effective_date": "2018-03-15",
        "file": "REGLEMENT-ARBITRAGE-CCJA-2017_fr.pdf",
        "publisher": "CCJA - Abidjan",
        "publication": "Journal Officiel de l'OHADA",
        "url": "https://www.ohada.org/ccja-arbitrage/",
        "description": "Règles de procédure d'arbitrage administré sous l'égide du centre d'arbitrage de la CCJA.",
    },
    "REGLEMENT-PROCEDURE-CCJA": {
        "code": "REGLEMENT-PROCEDURE-CCJA",
        "name": "Règlement de Procédure CCJA",
        "full_name": "Règlement de Procédure de la Cour Commune de Justice et d'Arbitrage de l'OHADA",
        "year": 2014,
        "adopted_at": "2014-01-30",
        "published_at": "2014-03-01",
        "effective_date": "2014-04-30",
        "file": "REGLEMENT-PROCEDURE-CCJA-2014_fr.pdf",
        "publisher": "CCJA - Abidjan",
        "publication": "Journal Officiel de l'OHADA",
        "url": "https://www.ohada.org/ccja-procedure/",
        "description": "Règles d'organisation, de saisine et de fonctionnement contentieux devant la CCJA.",
    },
}
